use rigspark_core::{
    catalog::Catalog,
    generation::GenerationCatalog,
    site_latest::{latest_items, latest_script},
};
use serde_json::{Value, json};

fn text_catalog() -> Catalog {
    let mut value: Value =
        serde_json::from_str(include_str!("../fixtures/catalog-baseline.json")).unwrap();
    value["schemaVersion"] = json!(3);
    value["generatedAt"] = json!("2026-10-07T03:17:00.000Z");
    let models = value["models"].as_array_mut().unwrap();
    let object = models[0].as_object_mut().unwrap();
    object.remove("releaseDate");
    object.remove("benchmarkProxy");
    object.insert("provenance".into(), json!("auto"));
    object.insert("addedAt".into(), json!("2026-10-06"));
    models[1]["releaseDate"] = json!("2026-09-10");
    Catalog::parse(&value.to_string()).unwrap()
}

#[test]
fn only_the_last_31_days_are_listed_with_display_facts_and_basis() {
    let text = text_catalog();
    let generation =
        GenerationCatalog::parse(include_str!("../fixtures/generation-baseline.json")).unwrap();
    let items = latest_items(&text, &generation).unwrap();
    let ids: Vec<&str> = items
        .iter()
        .map(|item| item["id"].as_str().unwrap())
        .collect();
    assert_eq!(ids.len(), 2, "{ids:?}");
    let auto = &items[0];
    assert_eq!(auto["kind"], "text");
    assert_eq!(auto["basis"], "added");
    assert_eq!(auto["date"], "2026-10-06");
    assert!(auto["memGiB"].as_f64().unwrap() > 0.0);
    assert_eq!(auto["runnable"], true);
    assert_eq!(items[1]["basis"], "released");
    for item in &items {
        let keys: Vec<&String> = item.as_object().unwrap().keys().collect();
        for key in &keys {
            assert!(
                [
                    "id",
                    "kind",
                    "label",
                    "memGiB",
                    "params",
                    "activeParams",
                    "dense",
                    "basis",
                    "date",
                    "runnable"
                ]
                .contains(&key.as_str()),
                "{key}"
            );
        }
    }
    assert!(
        !ids.iter()
            .any(|id| id.starts_with("flux1") || id.starts_with("wan2.1")),
        "2024/2025 generation releases are out of window"
    );
}

#[test]
fn the_script_is_deterministic_inert_data_for_a_self_only_csp() {
    let text = text_catalog();
    let generation =
        GenerationCatalog::parse(include_str!("../fixtures/generation-baseline.json")).unwrap();
    let script = latest_script(&text, &generation).unwrap();
    assert_eq!(script, latest_script(&text, &generation).unwrap());
    assert!(script.starts_with("// Generated by `cargo catalog-site`"));
    assert!(script.contains("globalThis.RIGSPARK_LATEST = Object.freeze("));
    assert!(script.contains("\"windowDays\":31"));
    assert!(
        !script.contains("</script"),
        "never closes an inline script"
    );
    let json_start = script.find("Object.freeze(").unwrap() + "Object.freeze(".len();
    let json_end = script.rfind(");").unwrap();
    let data: Value = serde_json::from_str(&script[json_start..json_end]).unwrap();
    assert_eq!(data["generatedAt"], "2026-10-07T03:17:00.000Z");
}
