use rigspark_core::{
    advice::decode_bytes,
    catalog::{Catalog, PerfDataset},
    generation::GenerationCatalog,
    site_latest::{
        hardware_classes, latest_items, latest_script, popular_ids, popular_items,
        stamp_catalog_counts,
    },
};
use serde_json::{Value, json};

fn text_catalog() -> Catalog {
    let mut value: Value =
        serde_json::from_str(include_str!("../fixtures/catalog-baseline.json")).unwrap();
    value["schemaVersion"] = json!(3);
    value["generatedAt"] = json!("2026-10-07T03:17:00.000Z");
    let models = value["models"].as_array_mut().unwrap();
    let object = models[0].as_object_mut().unwrap();
    object.remove("releaseDate");
    object.remove("benchmarkProxy");
    object.insert("provenance".into(), json!("auto"));
    object.insert("addedAt".into(), json!("2026-10-06"));
    models[1]["releaseDate"] = json!("2026-09-10");
    Catalog::parse(&value.to_string()).unwrap()
}

#[test]
fn only_the_last_31_days_are_listed_with_display_facts_and_basis() {
    let text = text_catalog();
    let generation =
        GenerationCatalog::parse(include_str!("../fixtures/generation-baseline.json")).unwrap();
    let items = latest_items(&text, &generation).unwrap();
    let ids: Vec<&str> = items
        .iter()
        .map(|item| item["id"].as_str().unwrap())
        .collect();
    assert_eq!(ids.len(), 2, "{ids:?}");
    let auto = &items[0];
    assert_eq!(auto["kind"], "text");
    assert_eq!(auto["basis"], "added");
    assert_eq!(auto["date"], "2026-10-06");
    assert!(auto["memGiB"].as_f64().unwrap() > 0.0);
    assert_eq!(auto["runnable"], true);
    assert_eq!(items[1]["basis"], "released");
    for item in &items {
        let keys: Vec<&String> = item.as_object().unwrap().keys().collect();
        for key in &keys {
            assert!(
                [
                    "id",
                    "kind",
                    "label",
                    "memGiB",
                    "params",
                    "activeParams",
                    "dense",
                    "basis",
                    "date",
                    "runnable",
                    "diskGiB",
                    "decodeBytes",
                    "totalGiB"
                ]
                .contains(&key.as_str()),
                "{key}"
            );
        }
    }
    assert!(
        !ids.iter()
            .any(|id| id.starts_with("flux1") || id.starts_with("wan2.1")),
        "2024/2025 generation releases are out of window"
    );
}

#[test]
fn the_script_is_deterministic_inert_data_for_a_self_only_csp() {
    let text = text_catalog();
    let generation =
        GenerationCatalog::parse(include_str!("../fixtures/generation-baseline.json")).unwrap();
    let perf = PerfDataset::parse(rigspark_core::PERF_JSON).unwrap();
    let popular = vec!["qwen3.5:4b".to_owned()];
    let script = latest_script(&text, &generation, &perf, &popular).unwrap();
    assert_eq!(
        script,
        latest_script(&text, &generation, &perf, &popular).unwrap()
    );
    assert!(script.starts_with("// Generated by `cargo catalog-site`"));
    assert!(script.contains("globalThis.RIGSPARK_LATEST = Object.freeze("));
    assert!(script.contains("\"windowDays\":31"));
    assert!(
        !script.contains("</script"),
        "never closes an inline script"
    );
    let json_start = script.find("Object.freeze(").unwrap() + "Object.freeze(".len();
    let json_end = script.rfind(");").unwrap();
    let data: Value = serde_json::from_str(&script[json_start..json_end]).unwrap();
    assert_eq!(data["generatedAt"], "2026-10-07T03:17:00.000Z");
    assert_eq!(data["popular"][0]["id"], "qwen3.5:4b");
    assert_eq!(
        data["hardware"].as_array().unwrap().len(),
        perf.classes.len()
    );
}

#[test]
fn catalog_counts_are_stamped_into_every_marker_and_nothing_else() {
    let text = text_catalog();
    let total = text.models.len();
    let html = "<p>Ranks all <span data-catalog-count=\"text\">69</span> models.</p>\n<dt><span data-catalog-count=\"text\">1</span></dt><dd>69 other</dd>";
    let stamped = stamp_catalog_counts(html, &text).unwrap();
    assert_eq!(
        stamped,
        format!(
            "<p>Ranks all <span data-catalog-count=\"text\">{total}</span> models.</p>\n<dt><span data-catalog-count=\"text\">{total}</span></dt><dd>69 other</dd>"
        )
    );
    assert_eq!(stamp_catalog_counts(&stamped, &text).unwrap(), stamped);
}

#[test]
fn catalog_count_stamping_fails_closed_on_missing_or_malformed_markers() {
    let text = text_catalog();
    for html in [
        "<p>Ranks all 69 models.</p>",
        "<span data-catalog-count=\"image\">3</span>",
        "<span data-catalog-count=\"text\">sixty</span>",
        "<span data-catalog-count=\"text\"></span>",
        "<span data-catalog-count=\"text\">69",
    ] {
        assert!(stamp_catalog_counts(html, &text).is_err(), "{html}");
    }
}

#[test]
fn the_published_site_states_the_shipped_catalog_size() {
    let text = Catalog::parse(rigspark_core::MODELS_JSON).unwrap();
    let site = include_str!("../../../site/index.html");
    assert_eq!(
        stamp_catalog_counts(site, &text).unwrap(),
        site,
        "site/index.html model counts are stale; run `cargo catalog-site`"
    );
}

fn text_fact<'a>(items: &'a [Value], id: &str) -> &'a Value {
    items.iter().find(|item| item["id"] == id).unwrap()
}

#[test]
fn text_facts_carry_disk_size_and_the_cli_decode_bytes_or_unknown() {
    let text = text_catalog();
    let generation =
        GenerationCatalog::parse(include_str!("../fixtures/generation-baseline.json")).unwrap();
    let items = latest_items(&text, &generation).unwrap();
    for model in text
        .models
        .iter()
        .filter(|model| items.iter().any(|item| item["id"] == model.id.as_str()))
    {
        let item = text_fact(&items, &model.id);
        let quant = &model.quantizations[0];
        let expected_disk = (quant.disk_bytes / 1_073_741_824.0 * 10.0).round() / 10.0;
        assert_eq!(
            item["diskGiB"].as_f64().unwrap(),
            expected_disk,
            "{}",
            model.id
        );
        match decode_bytes(model, quant).unwrap() {
            Some(bytes) => assert_eq!(item["decodeBytes"].as_f64().unwrap(), bytes),
            None => assert!(item["decodeBytes"].is_null(), "{}", model.id),
        }
    }
    // Q1_0 has no sourced throughput, so the site must not estimate speed for it.
    assert!(text_fact(&items, "bonsai:8b")["decodeBytes"].is_null());
    // MoE speed follows active, not total, parameters: 3B at Q4 (4.7 bits) per token.
    assert_eq!(
        text_fact(&items, "qwen3.6:35b")["decodeBytes"]
            .as_f64()
            .unwrap(),
        (3e9_f64 * 4.7 / 8.0).ceil()
    );
}

#[test]
fn generation_facts_carry_largest_and_total_download_size() {
    let text = text_catalog();
    let mut generation: Value =
        serde_json::from_str(include_str!("../fixtures/generation-baseline.json")).unwrap();
    for model in generation["models"].as_array_mut().unwrap() {
        model["releaseDate"] = json!("2026-10-01");
    }
    let generation = GenerationCatalog::parse(&generation.to_string()).unwrap();
    let items = latest_items(&text, &generation).unwrap();
    let gib = |bytes: u64| (bytes as f64 / 1_073_741_824.0 * 10.0).round() / 10.0;
    for model in &generation.models {
        let item = text_fact(&items, &model.id);
        assert_eq!(item["memGiB"].as_f64().unwrap(), gib(model.largest_bytes()));
        assert_eq!(item["totalGiB"].as_f64().unwrap(), gib(model.total_bytes()));
        assert_eq!(item["diskGiB"], item["totalGiB"]);
        assert!(item["decodeBytes"].is_null());
    }
}

#[test]
fn popular_facts_come_from_the_catalog_in_page_order_and_unknown_ids_fail() {
    let text = text_catalog();
    let ids = vec!["qwen3.5:4b".to_owned(), "qwen3.6:35b".to_owned()];
    let items = popular_items(&text, &ids).unwrap();
    assert_eq!(
        items
            .iter()
            .map(|item| item["id"].as_str().unwrap())
            .collect::<Vec<_>>(),
        ["qwen3.5:4b", "qwen3.6:35b"]
    );
    let moe = &items[1];
    assert_eq!(moe["dense"], false);
    assert_eq!(moe["activeParams"], "3B");
    assert!(moe["memGiB"].as_f64().unwrap() > moe["diskGiB"].as_f64().unwrap());
    assert!(popular_items(&text, &["no-such-model".to_owned()]).is_err());
    assert!(popular_items(&text, &[]).is_err());
}

#[test]
fn popular_ids_are_read_from_page_markers_and_fail_closed() {
    let html = r#"<button data-popular="llama3.1:8b">L</button><b>x</b><button data-popular="qwen3:14b">Q</button>"#;
    assert_eq!(popular_ids(html).unwrap(), ["llama3.1:8b", "qwen3:14b"]);
    for broken in [
        "<p>none</p>",
        r#"<b data-popular="">x</b>"#,
        r#"<b data-popular="a b">x</b>"#,
        r#"<b data-popular="x"#,
    ] {
        assert!(popular_ids(broken).is_err(), "{broken}");
    }
}

#[test]
fn hardware_classes_mirror_the_sourced_perf_dataset_for_the_default_backend() {
    let perf = PerfDataset::parse(rigspark_core::PERF_JSON).unwrap();
    let classes = hardware_classes(&perf);
    assert_eq!(classes.len(), perf.classes.len());
    for (class, item) in perf.classes.iter().zip(&classes) {
        assert_eq!(item["id"], class.id.as_str());
        assert_eq!(item["vendor"], class.vendor.as_str());
        assert_eq!(item["kind"], class.kind.as_str());
        assert_eq!(
            item["bandwidthGBps"].as_f64().unwrap(),
            class.mem_bandwidth_gbps
        );
        assert_eq!(item["minBytes"].as_f64().unwrap(), class.min_bytes);
        assert_eq!(item["maxBytes"].as_f64().unwrap(), class.max_bytes);
        let ollama = class
            .efficiency_by_backend
            .as_ref()
            .and_then(|values| values.get("ollama"))
            .copied()
            .unwrap_or(class.efficiency);
        assert_eq!(item["efficiency"].as_f64().unwrap(), ollama);
        assert!(item.get("sources").is_none(), "keep the page payload small");
    }
}

#[test]
fn the_published_site_popular_models_exist_in_the_catalog() {
    let text = Catalog::parse(rigspark_core::MODELS_JSON).unwrap();
    let ids = popular_ids(include_str!("../../../site/index.html")).unwrap();
    assert!(ids.len() >= 4, "{ids:?}");
    popular_items(&text, &ids).unwrap();
}
