pub mod acquire;
pub mod adapters;
pub mod agent;
pub mod application;
pub mod cache;
pub mod catalog_proposals;
pub mod catalog_quality;
pub mod catalog_update;
pub mod chat_service;
pub mod command;
pub mod context;
pub mod coverage;
pub mod diagnostics;
pub mod generation;
pub mod hardware;
pub mod harness;
pub mod harness_registry;
pub mod http;
pub mod identity;
pub mod library;
pub mod lifecycle;
pub mod mcp;
mod mcp_framing;
mod mcp_http;
mod mcp_legacy;
pub mod mcp_sdk;
pub mod memory;
pub mod memory_backend;
pub mod migration_service;
pub mod native_chat;
pub mod native_runtime;
pub mod ollama_inference;
pub mod ollama_installed;
pub mod openai;
pub mod opencode;
pub mod process_control;
pub mod pull;
mod redaction;
pub mod registry_collector;
pub mod runs;
pub mod secure_fs;
pub mod sessions;
pub mod special_adapters;
pub mod state;
pub mod tool_policy;
pub mod usage;
pub mod workspace;
pub mod workspace_git;
