//! Static last-month model data for the website's Ask Sparky panel.

use crate::{
    catalog::{Catalog, RecencyBasis, date},
    generation::GenerationCatalog,
    sizing::ValidationError,
};
use serde_json::{Value, json};

pub const WINDOW_DAYS: i64 = 31;
const GIB: f64 = 1_073_741_824.0;

fn basis(basis: RecencyBasis) -> &'static str {
    match basis {
        RecencyBasis::Released => "released",
        RecencyBasis::Added => "added",
    }
}

fn gib(bytes: f64) -> f64 {
    (bytes / GIB * 10.0).round() / 10.0
}

/// Text, image and video entries whose recency date is within 31 days of the text catalog's
/// `generatedAt`, newest first. Each item carries only what the site displays.
pub fn latest_items(
    text: &Catalog,
    generation: &GenerationCatalog,
) -> Result<Vec<Value>, ValidationError> {
    let reference = date(text.generated_at.get(..10).unwrap_or_default())?;
    let cutoff = reference - time::Duration::days(WINDOW_DAYS);
    let recent = |day: &str| date(day).is_ok_and(|day| day >= cutoff && day <= reference);
    let mut items = Vec::new();
    for model in &text.models {
        let Some((day, why)) = model.recency() else {
            continue;
        };
        if !recent(day) {
            continue;
        }
        // The default (pulled) quantization is what `rigspark up` installs.
        let index = crate::registry_collector::pulled_quantization(model).unwrap_or(0);
        let quant = &model.quantizations[index];
        let mut item = json!({
            "id": model.id,
            "kind": "text",
            "label": format!("{} · {}", model.id, quant.name),
            "memGiB": gib(quant.min_ram_bytes),
            "params": model.params,
            "dense": matches!(model.architecture, crate::sizing::Architecture::Dense),
            "basis": basis(why),
            "date": day,
            "runnable": true,
        });
        if let Some(active) = &model.active_params {
            item["activeParams"] = json!(active);
        }
        items.push(item);
    }
    for model in &generation.models {
        let Some((day, why)) = model.recency() else {
            continue;
        };
        if !recent(day) {
            continue;
        }
        items.push(json!({
            "id": model.id,
            "kind": model.kind.name(),
            "label": model.id,
            // Generation fit is decided by the largest weight file (ComfyUI swaps stages).
            "memGiB": gib(model.largest_bytes() as f64),
            "params": model.params,
            "dense": true,
            "basis": basis(why),
            "date": day,
            "runnable": model.workflow.is_some(),
        }));
    }
    items.sort_by(|left, right| {
        right["date"]
            .as_str()
            .cmp(&left["date"].as_str())
            .then_with(|| left["id"].as_str().cmp(&right["id"].as_str()))
    });
    Ok(items)
}

/// `site/data/latest.js`: inert, deterministic data loaded under `script-src 'self'`.
pub fn latest_script(
    text: &Catalog,
    generation: &GenerationCatalog,
) -> Result<String, ValidationError> {
    let data = json!({
        "generatedAt": text.generated_at,
        "windowDays": WINDOW_DAYS,
        "models": latest_items(text, generation)?,
    });
    let encoded = serde_json::to_string(&data)
        .map_err(|error| ValidationError(error.to_string()))?
        .replace('<', "\\u003c");
    Ok(format!(
        "// Generated by `cargo catalog-site` from the shipped catalogs. Do not edit.\nglobalThis.RIGSPARK_LATEST = Object.freeze({encoded});\n"
    ))
}

const COUNT_MARKER: &str = "<span data-catalog-count=\"";

/// Rewrites every `<span data-catalog-count="text">N</span>` in the site HTML with the number of
/// text models in the catalog, so published counts cannot drift from what `recommend` ranks.
/// Fails when no marker exists, or a marker names an unknown kind or holds anything but digits.
pub fn stamp_catalog_counts(html: &str, text: &Catalog) -> Result<String, ValidationError> {
    let invalid = |reason: &str| ValidationError(format!("site catalog count: {reason}"));
    let total = text.models.len().to_string();
    let mut output = String::with_capacity(html.len());
    let mut rest = html;
    let mut markers = 0;
    while let Some(start) = rest.find(COUNT_MARKER) {
        let after_marker = &rest[start + COUNT_MARKER.len()..];
        let kind_end = after_marker
            .find("\">")
            .ok_or_else(|| invalid("unterminated marker"))?;
        if &after_marker[..kind_end] != "text" {
            return Err(invalid("unknown kind"));
        }
        let content = &after_marker[kind_end + 2..];
        let value_end = content
            .find("</span>")
            .ok_or_else(|| invalid("unclosed marker"))?;
        let value = &content[..value_end];
        if value.is_empty() || !value.bytes().all(|byte| byte.is_ascii_digit()) {
            return Err(invalid("marker must hold a number"));
        }
        let open_len = start + COUNT_MARKER.len() + kind_end + 2;
        output.push_str(&rest[..open_len]);
        output.push_str(&total);
        rest = &content[value_end..];
        markers += 1;
    }
    if markers == 0 {
        return Err(invalid("no data-catalog-count markers found"));
    }
    output.push_str(rest);
    Ok(output)
}
